# Generated by Django 5.1.4 on 2024-12-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_carro_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='color',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
