# Generated by Django 5.1.4 on 2025-01-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_autor_libro_autores_atrib'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('biografia', models.TextField(max_length=500)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.autor')),
            ],
        ),
    ]
